import { Router } from 'express';
import authRoutes from './auth.routes';
import companyRoutes from './company.routes';
import customerRoutes from './customer.routes';
import vendorRoutes from './vendor.routes';
import productRoutes from './product.routes';
import invoiceRoutes from './invoice.routes';
import purchaseRoutes from './purchase.routes';
import inventoryAdjustmentRoutes from './inventory-adjustment.routes';
import supportRoutes from './support.routes';
import ledgerRoutes from './ledger.routes';
import dashboardRoutes from './dashboard.routes';
import reportRoutes from './report.routes';
import lookupRoutes from './lookup.routes';
import userRoutes from './user.routes';
import settingRoutes from './setting.routes';
import notificationRoutes from './notification.routes';
import apiLogRoutes from './apiLog.routes';
import fbrTokenRoutes from './fbrToken.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/companies', companyRoutes);
router.use('/customers', customerRoutes);
router.use('/vendors', vendorRoutes);
router.use('/products', productRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/purchases', purchaseRoutes);
router.use('/inventory-adjustments', inventoryAdjustmentRoutes);
router.use('/support', supportRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportRoutes);
router.use('/lookup', lookupRoutes);
router.use('/admin', userRoutes);
router.use('/settings', settingRoutes);
router.use('/notifications', notificationRoutes);
router.use('/api-logs', apiLogRoutes);
router.use('/fbr-tokens', fbrTokenRoutes);

export default router;
